
faye_app_config:
    path: "%cravler_faye_app.config.route_url_prefix%/config.json"
    defaults: { _controller: CravlerFayeAppBundle:App:config }

faye_app_init:
    path: "%cravler_faye_app.config.route_url_prefix%/init.js"
    defaults: { _controller: CravlerFayeAppBundle:App:init }

faye_app_security:
    path: "%cravler_faye_app.config.route_url_prefix%/security"
    defaults: { _controller: CravlerFayeAppBundle:App:security }

faye_app_status:
    path: "%cravler_faye_app.config.route_url_prefix%/status"
    defaults: { _controller: CravlerFayeAppBundle:App:status }

faye_app_example:
    path: "%cravler_faye_app.config.route_url_prefix%/example/{type}"
    defaults: { _controller: CravlerFayeAppBundle:App:example, type: ~ }
